FROM ubuntu:18.04
RUN apt-get update -y
RUN apt-get install --yes curl
RUN apt-get install --yes gnupg
RUN curl --silent --location https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install --yes nodejs
RUN apt-get install --yes build-essential
